import type { QuestionBlueprint } from './blueprint';

export const GRADE_BLUEPRINTS: Record<string, QuestionBlueprint[]> = {
  '5': [
    { id: 1, topic: "Natural sonlar va amallar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Oddiy va o'nli kasrlar", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Foiz va nisbat", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Matnli masalalar", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "Geometriya (Yuz va perimetr)", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Tenglama va tengsizliklar", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Shakllar ketma-ketligi", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Raqamlar qonuniyati", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Mantiqiy shartlar (Agar... unda...)", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Fazoviy tasavvur (Kubiklar)", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Yolg'on/Rost tasdiqlar", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Murakkab qonuniyatlar", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Grafik va jadvallar", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Sabab-oqibat tahlili", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Taqqoslash va sintez", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Kombinatorika elementlari", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Matndagi axborotni ajratish", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Xulosa chiqarish", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "So'z boyligi (Sinonim/Antonim)", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Matnni tushunish", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Grammatik qonuniyatlar", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Mantiqiy bog'liqlik (Analogiya)", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Xatolarni topish", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Fikrni mantiqiy tugallash", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "G'ayrioddiy yechimlar", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Berilganlardan yangi shart tuzish", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Shakllardan butun yasash", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Alternativ ssenariylar", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Ochiq savollar (Kreativ o'ylash)", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Mavzu bo'yicha assotsiatsiya", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '6': [
    { id: 1, topic: "Butun sonlar bilan amallar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Ratsional sonlar", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Proportsiya", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Burchaklar va uchburchaklar", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "O'zgaruvchili ifodalar", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Chiziqli tenglamalar", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Murakkab ketma-ketliklar", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Shifrlar va kodlar", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Venn diagrammalari", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Fikrlashdagi ziddiyatlar", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Geometrik mantiq", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Vaqt va tezlik mantiqlari", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Diagrammalar tahlili", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Ko'p parametrli taqqoslash", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Tarkibiy tahlil", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Shartli ehtimollik kirish", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Ma'lumotlarni filtrlash", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Algoritmik qadamlar", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Murakkab sinonimiya", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Matn ma'nosini umumlashtirish", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "So'z yasalishi", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Matndagi yashirin ma'no", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Mantiqiy uzviylik", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Frazeologizmlar", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Muammoga nostandart yechim", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Naqshlar yaratish", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Matnni o'zgartirish", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Kreativ kombinatsiya", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Shartlarni o'zgartirib yechish", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Yangi analogiya kashf etish", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '7': [
    { id: 1, topic: "Ko'phadlar va amallar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Qisqa ko'paytirish formulalari", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Chiziqli funksiya", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Uchburchaklar xossalari", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "Tenglamalar sistemasi", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Geometrik qurishlar", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Deduksiya", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Ko'p shartli masalalar", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Murakkab kodlarni ochish", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Fazoviy aylantirish", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Matematik jumboqlar", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Strategik o'yin mantiqi", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Statistik ma'lumotlar", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Algoritmik tahlil", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Ehtimollik va hodisalar", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Gipotezalarni tekshirish", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Trendlarni aniqlash", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Kompleks xulosa", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Matn uslublari", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Asosiy g'oyani izohlash", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Murakkab analogiyalar", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Mantiqiy xatolar", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Argumentlarni baholash", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "So'z ma'nosini ko'chirish", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Ochiq muammolarni xal qilish", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Innovatsion dizayn", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Matnni boshqa janrda yozish", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Murakkab naqshlar", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Noan'anaviy strategiyalar", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Assotsiativ fikrlash", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '8': [
    { id: 1, topic: "Kvadrat ildizlar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Kvadrat tenglamalar", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Kvadrat funksiya", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Pifagor teoremasi", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "To'rtburchaklar xossalari", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Tengsizliklar sistemasi", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Induksiya va deduksiya", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Paradokslar", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Matematik mantiq", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Qurilish mantiqi", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Syllogizmlar", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Tizimli mantiq", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Kombinatorika", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Murakkab ehtimollik", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Ilmiy matn tahlili", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Ma'lumotlar modellashtirish", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Argumentlarni sintezlash", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Kritik tahlil", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Ilmiy atamalar", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Matnni tanqidiy baholash", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Abstrakt analogiyalar", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Matn tuzilishi", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Ritorik figuralar", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Nuqtai nazarni o'zgartirish", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Texnik kreativlik", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Gipoteza yaratish", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Murakkab tizimlarni o'zgartirish", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Alternativ modellar", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Kreativ yozish", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Vizual kreativlik", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '9': [
    { id: 1, topic: "Kvadratik funksiyalar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Aylana va doira", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Progressiyalar (Arifmetik/Geometrik)", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Trigonometriyaga kirish", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "Vektorlar", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Tenglamalar sistemasi tahlili", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Algoritm tuzish", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Mantiqiy sxemalar", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Matematik isbotlar", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Ko'p o'lchovli mantiq", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Strukturaviy mantiq", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Kriptografiya asoslari", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Funksiyalar grafiklari tahlili", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Ehtimollik tarqalishi", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Ilmiy tadqiqot tahlili", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Tizimli muammolar", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Ko'p o'zgaruvchili taqqoslash", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Mantiqiy paradokslar", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Falsafiy matnlar", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Murakkab argumentatsiya", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Kritik o'qish", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Kontekstual ma'no", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Ritorik tahlil", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Debat mantiqi", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Innovatsion loyihalash", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Murakkab ixtirolar", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Tizimli kreativlik", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "G'oyalar sintezi", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Nostandart strategiyalar", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Mavhum kreativlik", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '10': [
    { id: 1, topic: "Trigonometrik funksiyalar", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Trigonometrik tenglamalar", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Ko'rsatkichli funksiyalar", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Logarifmlar", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "Stereometriya asoslari", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Ehtimollik nazariyasi", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Murakkab algoritmik mantiq", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Teoremalar isboti", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Matematik induksiya", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Ko'p qatlamli mantiq", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Fazoviy modellashtirish", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Kognitiv jumboqlar", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Murakkab statistik tahlil", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Matematik modellashtirish", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Ilmiy maqolalar tahlili", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Tizimli tahlil", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Eksperimental ma'lumotlar", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Kompleks qaror qabul qilish", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Akademik o'qish", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Diskurs tahlili", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Abstrakt mantiqiy matnlar", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Dalillarni tanqid qilish", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Sintaktik murakkablik", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Mantiqiy bog'lanishlar", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Nazariyalarni birlashtirish", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Abstrakt modellar yaratish", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Kreativ muammo yechish", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Innovatsion konsepsiyalar", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Nostandart isbotlar", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Yangi metodikalar", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
  '11': [
    { id: 1, topic: "Hosila va uning tatbiqi", category: "math", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 2, topic: "Integral va uning tatbiqi", category: "math", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 3, topic: "Ko'p yoqliklar (Prizma, Piramida)", category: "math", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 4, topic: "Aylanma jismlar", category: "math", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 5, topic: "Kompleks sonlar", category: "math", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 6, topic: "Kombinatorika va Ehtimollik (Murakkab)", category: "math", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 7, topic: "Yuqori darajadagi mantiq", category: "logic", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 8, topic: "Murakkab isbot masalalari", category: "logic", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 9, topic: "Topologik mantiq", category: "logic", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 10, topic: "Fazoviy tafakkur (3D)", category: "logic", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 11, topic: "Analitik geometriya mantiqi", category: "logic", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 12, topic: "Matematik falsafa", category: "logic", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 13, topic: "Oliy matematika tatbiqi", category: "analytical", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 14, topic: "Murakkab ilmiy tahlil", category: "analytical", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 15, topic: "Global muammolar tahlili", category: "analytical", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 16, topic: "Tizimli dinamika", category: "analytical", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 17, topic: "Ekspertiza va baholash", category: "analytical", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 18, topic: "Xulosalarni sintezlash", category: "analytical", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 19, topic: "Oliy darajadagi akademik matnlar", category: "verbal", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 20, topic: "Falsafiy va ilmiy argumentlar", category: "verbal", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 21, topic: "Matnni chuqur tanqidiy tahlil qilish", category: "verbal", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 22, topic: "Konsepsiyalarni taqqoslash", category: "verbal", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 23, topic: "Ritorik va mantiqiy tuzilmalar", category: "verbal", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 24, topic: "Sintaktik tahlil", category: "verbal", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
    { id: 25, topic: "Ilmiy tadqiqot g'oyalari", category: "creativity", difficulty: "Oson", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "45s" },
    { id: 26, topic: "Yangi teoremalar kashf etish", category: "creativity", difficulty: "Oson", skill: "Qo'llash", thinkingType: "Analitik", timeEstimate: "45s" },
    { id: 27, topic: "Murakkab tizimlarni modellashtirish", category: "creativity", difficulty: "O'rta", skill: "Tahlil qilish", thinkingType: "Induktiv", timeEstimate: "1min 30s" },
    { id: 28, topic: "Global muammolarga innovatsion yechimlar", category: "creativity", difficulty: "O'rta", skill: "Baholash", thinkingType: "Deduktiv", timeEstimate: "1min 30s" },
    { id: 29, topic: "Abstrakt kognitiv modellar", category: "creativity", difficulty: "Qiyin", skill: "Sintezlash", thinkingType: "Fazoviy", timeEstimate: "2min" },
    { id: 30, topic: "Kreativ sintez", category: "creativity", difficulty: "Qiyin", skill: "Tushunish", thinkingType: "Deduktiv", timeEstimate: "2min" },
  ],
};
